[workspace]
members = [
    "struthionidae",
    "x001-async-await-and-custom-test-framework",
    "x002-string-caching-and-interning",
    "x003-arenas-and-bytes",
    "x004-rust-shell-scripting",
 ]

exclude = [
    "x005-trees",
    
]