[package]
name = "symbol-tree"
version = "0.1.0"
authors = ["dillon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "^0.5.6"
owning_ref = "0.4.1"
itertools = "0.9.0"
